<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: taskrpc.proto

namespace Hepburn\BridgeSidecar\Request\Grpc\Protos\Task;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>task.TaskRequest</code>
 */
class TaskRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string app = 1;</code>
     */
    protected $app = '';
    /**
     * Generated from protobuf field <code>string jobName = 2;</code>
     */
    protected $jobName = '';
    /**
     * Generated from protobuf field <code>string params = 3;</code>
     */
    protected $params = '';
    /**
     * Generated from protobuf field <code>int64 delay = 4;</code>
     */
    protected $delay = 0;
    /**
     * Generated from protobuf field <code>string method = 5;</code>
     */
    protected $method = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $app
     *     @type string $jobName
     *     @type string $params
     *     @type int|string $delay
     *     @type string $method
     * }
     */
    public function __construct($data = NULL) {
        \Hepburn\BridgeSidecar\Request\Grpc\Protos\Task\Taskrpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string app = 1;</code>
     * @return string
     */
    public function getApp()
    {
        return $this->app;
    }

    /**
     * Generated from protobuf field <code>string app = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setApp($var)
    {
        GPBUtil::checkString($var, True);
        $this->app = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string jobName = 2;</code>
     * @return string
     */
    public function getJobName()
    {
        return $this->jobName;
    }

    /**
     * Generated from protobuf field <code>string jobName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setJobName($var)
    {
        GPBUtil::checkString($var, True);
        $this->jobName = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string params = 3;</code>
     * @return string
     */
    public function getParams()
    {
        return $this->params;
    }

    /**
     * Generated from protobuf field <code>string params = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setParams($var)
    {
        GPBUtil::checkString($var, True);
        $this->params = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 delay = 4;</code>
     * @return int|string
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     * Generated from protobuf field <code>int64 delay = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

}

